name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  go-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: pipery-dev/pipery-golang-ci@v1
        with:
          project_path: .
          go_version: "1.22"
          skip_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          image_name: ghcr.io/pipery-dev/runner
          release_docker_image: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          docker_push_latest: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
